// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SklepGrovly;

#nullable disable

namespace SklepGrovly.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260712192911_AddDeliveryAddressToOrder")]
    partial class AddDeliveryAddressToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SklepGrovly.Entities.Kategoria", b =>
                {
                    b.Property<int>("Id_Kategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Kategoria"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id_Kategoria");

                    b.ToTable("Kategoria");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Koszyk", b =>
                {
                    b.Property<int>("Id_Koszyk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Koszyk"));

                    b.Property<int>("Id_Klient")
                        .HasColumnType("int");

                    b.HasKey("Id_Koszyk");

                    b.HasIndex("Id_Klient")
                        .IsUnique();

                    b.ToTable("Koszyk");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Opinia", b =>
                {
                    b.Property<int>("Id_Opinia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Opinia"));

                    b.Property<DateTime>("DataWystawienia")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Klient")
                        .HasColumnType("int");

                    b.Property<int>("Id_Produkt")
                        .HasColumnType("int");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id_Opinia");

                    b.HasIndex("Id_Produkt");

                    b.HasIndex("Id_Klient", "Id_Produkt")
                        .IsUnique();

                    b.ToTable("Opinia");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Osoba", b =>
                {
                    b.Property<int>("Id_Osoba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Osoba"));

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrTelefonu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TypOsoby")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id_Osoba");

                    b.ToTable("Osoba");

                    b.HasDiscriminator<string>("TypOsoby").HasValue("Osoba");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SklepGrovly.Entities.Platnosc", b =>
                {
                    b.Property<int>("Id_Platnosc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Platnosc"));

                    b.Property<DateTime>("DataPlatnosci")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdZBramkiPlatniczej")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Id_Zamowienie")
                        .HasColumnType("int");

                    b.Property<decimal>("KwotaPlatnosci")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetodaPlatnosci")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusPlatnosci")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Platnosc");

                    b.HasIndex("Id_Zamowienie")
                        .IsUnique();

                    b.ToTable("Platnosc");
                });

            modelBuilder.Entity("SklepGrovly.Entities.PozycjaWKoszyku", b =>
                {
                    b.Property<int>("Id_Pozycja_Koszyk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pozycja_Koszyk"));

                    b.Property<int>("Id_Koszyk")
                        .HasColumnType("int");

                    b.Property<int>("Id_Produkt")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.HasKey("Id_Pozycja_Koszyk");

                    b.HasIndex("Id_Koszyk");

                    b.HasIndex("Id_Produkt");

                    b.ToTable("PozycjeWKoszyku");
                });

            modelBuilder.Entity("SklepGrovly.Entities.PozycjaWZamowieniu", b =>
                {
                    b.Property<int>("Id_Pozycja_Zamowienie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pozycja_Zamowienie"));

                    b.Property<decimal>("CenaZakupu")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Id_Produkt")
                        .HasColumnType("int");

                    b.Property<int>("Id_Zamowienie")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.HasKey("Id_Pozycja_Zamowienie");

                    b.HasIndex("Id_Produkt");

                    b.HasIndex("Id_Zamowienie");

                    b.ToTable("PozycjeWZamowieniu");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Produkt", b =>
                {
                    b.Property<int>("Id_Produkt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Produkt"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("bit");

                    b.Property<int?>("Id_Kategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IloscNaStanie")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Znizka")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_Produkt");

                    b.HasIndex("Id_Kategoria");

                    b.ToTable("Produkt");
                });

            modelBuilder.Entity("SklepGrovly.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Osoba")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Osoba");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SklepGrovly.Entities.Zamowienie", b =>
                {
                    b.Property<int>("Id_Zamowienie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Zamowienie"));

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Klient")
                        .HasColumnType("int");

                    b.Property<string>("ImieOdbiorcy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NazwiskoOdbiorcy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NrDomu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonOdbiorcy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Zamowienie");

                    b.HasIndex("Id_Klient");

                    b.ToTable("Zamowienie");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Administrator", b =>
                {
                    b.HasBaseType("SklepGrovly.Entities.Osoba");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Klient", b =>
                {
                    b.HasBaseType("SklepGrovly.Entities.Osoba");

                    b.HasDiscriminator().HasValue("Klient");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Koszyk", b =>
                {
                    b.HasOne("SklepGrovly.Entities.Klient", "Klient")
                        .WithOne("Koszyk")
                        .HasForeignKey("SklepGrovly.Entities.Koszyk", "Id_Klient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Opinia", b =>
                {
                    b.HasOne("SklepGrovly.Entities.Klient", "Klient")
                        .WithMany("Opinie")
                        .HasForeignKey("Id_Klient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SklepGrovly.Entities.Produkt", "Produkt")
                        .WithMany("Opinie")
                        .HasForeignKey("Id_Produkt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Platnosc", b =>
                {
                    b.HasOne("SklepGrovly.Entities.Zamowienie", "Zamowienie")
                        .WithOne("Platnosc")
                        .HasForeignKey("SklepGrovly.Entities.Platnosc", "Id_Zamowienie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zamowienie");
                });

            modelBuilder.Entity("SklepGrovly.Entities.PozycjaWKoszyku", b =>
                {
                    b.HasOne("SklepGrovly.Entities.Koszyk", "Koszyk")
                        .WithMany("PozycjeWKoszyku")
                        .HasForeignKey("Id_Koszyk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SklepGrovly.Entities.Produkt", "Produkt")
                        .WithMany("PozycjaWKoszyku")
                        .HasForeignKey("Id_Produkt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Koszyk");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("SklepGrovly.Entities.PozycjaWZamowieniu", b =>
                {
                    b.HasOne("SklepGrovly.Entities.Produkt", "Produkt")
                        .WithMany("PozycjaWZamowieniu")
                        .HasForeignKey("Id_Produkt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SklepGrovly.Entities.Zamowienie", "Zamowienie")
                        .WithMany("PozycjaWZamowieniu")
                        .HasForeignKey("Id_Zamowienie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");

                    b.Navigation("Zamowienie");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Produkt", b =>
                {
                    b.HasOne("SklepGrovly.Entities.Kategoria", "Kategoria")
                        .WithMany("Produkty")
                        .HasForeignKey("Id_Kategoria")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("SklepGrovly.Entities.RefreshToken", b =>
                {
                    b.HasOne("SklepGrovly.Entities.Osoba", "Osoba")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("Id_Osoba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osoba");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Zamowienie", b =>
                {
                    b.HasOne("SklepGrovly.Entities.Klient", "Klient")
                        .WithMany("Zamowienia")
                        .HasForeignKey("Id_Klient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Kategoria", b =>
                {
                    b.Navigation("Produkty");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Koszyk", b =>
                {
                    b.Navigation("PozycjeWKoszyku");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Osoba", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Produkt", b =>
                {
                    b.Navigation("Opinie");

                    b.Navigation("PozycjaWKoszyku");

                    b.Navigation("PozycjaWZamowieniu");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Zamowienie", b =>
                {
                    b.Navigation("Platnosc")
                        .IsRequired();

                    b.Navigation("PozycjaWZamowieniu");
                });

            modelBuilder.Entity("SklepGrovly.Entities.Klient", b =>
                {
                    b.Navigation("Koszyk")
                        .IsRequired();

                    b.Navigation("Opinie");

                    b.Navigation("Zamowienia");
                });
#pragma warning restore 612, 618
        }
    }
}
